[package]
name = "rust-ethereum-study"
version = "0.1.0"
authors = ["HG <hgmaxwellking@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.0" }
web3 = "0.15.0"
